import _ from "@lodash";
/**
 * The product model.
 */
const CompanyModel = (data) => {
  return _.defaults(data || {}, {
    id: _.uniqueId("company-"),
    name: "",
    handle: "",
    description: "",
    categories: [],
    tags: [],
    featuredImageId: "",
    images: [],
    priceTaxExcl: 0,
    priceTaxIncl: 0,
    taxRate: 0,
    comparedPrice: 0,
    quantity: 0,
    sku: "",
    width: "",
    height: "",
    depth: "",
    weight: "",
    extraShippingFee: 0,
    price: "",
    active: true,
    image: "",
    registrantUserId: 0,
    total: "",
    officeLocation: data.officeLocation || "",
    factoryLocation: data.factoryLocation || "",
    officePoBox: data.officePoBox || "",
    factoryPoBox: data.factoryPoBox || "",
    officeState: data.officeState || "",
    officeCity: data.officeCity || "",
    factoryState: data.factoryState || "",
    factoryCity: data.factoryCity || "",
    industrialCity: data.industrialCity || "",
    country: data.country || "ایران",
    latitude: data.latitude || null,
    longitude: data.longitude || null,
    fullAddress: data.fullAddress || "",
    commonName: data.commonName || "",
	companyLogoFiles: data.companyLogoFiles || [],
    companyBackgroundImages: data.companyBackgroundImages || [],
    companyCertificates: data.companyCertificates || [],
    companyGalleryDocument: data.companyGalleryDocument || [],
    companyGalleryProduct: data.companyGalleryProduct || [],
    companyGalleryContact: data.companyGalleryContact || [],
    companyGalleryCatalog: data.companyGalleryCatalog || [],
    companyGallerySlider: data.companyGallerySlider || [],
  });
};
export default CompanyModel;
